- name: Install zsh from Pacman
  become: true
  become_user: root
  community.general.pacman:
    name: zsh
    update_cache: true
  tags: [zsh, dotfiles]
- name: Installing stow
  become: true
  become_user: root
  community.general.pacman:
    name: stow
    update_cache: true
  tags: [dotfiles, stow]
- name: Install tmux
  become: true
  become_user: root
  community.general.pacman:
    name: tmux
    update_cache: true
  tags: [tmux, dotfiles]
- name: Install fzf
  become: true
  become_user: root
  community.general.pacman:
    name: fzf
    update_cache: true
  tags: [addons]
- name: Core tasks
  ansible.builtin.include_tasks:
    file: tasks/arch-core.yml
    apply:
      tags: [core, nvim, dotfiles]
  tags: always
