- name: Zsh tasks
  ansible.builtin.include_tasks:
    file: tasks/zsh.yml
    include:
    tags:
      - zsh
      - dotfiles
  tags: always
- name: Dotfiles tasks
  ansible.builtin.include_tasks:
    file: tasks/dotfiles.yml
    include:
    tags:
      - dotfiles
      - stow
  tags: always
- name: SSH tasks
  ansible.builtin.include_tasks:
    file: tasks/ssh.yml
    include:
    tags:
      - ssh
      - dotfiles
  tags: always
- name: Cargo tasks
  ansible.builtin.include_tasks:
    file: tasks/rust.yml
    include:
    tags:
      - rust
      - node
      - addons
  tags: always
- name: Node tasks
  ansible.builtin.include_tasks:
    file: tasks/node.yml
    include:
    tags:
      - node
  tags: always
- name: Tmux tasks
  ansible.builtin.include_tasks:
    file: tasks/tmux.yml
    include:
    tags:
      - tmux
      - dotfiles
  tags: always
- name: Neovim tasks
  ansible.builtin.include_tasks:
    file: tasks/nvim.yml
    include:
    tags:
      - nvim
      - dotfiles
  tags: always
- name: Addons tasks
  ansible.builtin.include_tasks:
    file: tasks/addons.yml
    include:
    tags:
      - addons
  tags: always
