- name: Terminal tasks
  ansible.builtin.include_tasks:
    file: tasks/linux/terminal.yml
    apply:
      tags: [terminal, kitty, desktop]
  tags: always
- name: Stow linux desktop dotfiles
  shell: cd $HOME/.dotfiles && zsh linux-desktop
  tags: [desktop]
