- name: Install Packages for dotfiles
  community.general.homebrew:
    name: [ripgrep, fd, fzf, tmux, stow, zsh, yabai]
    state: latest
  tags: dotfiles
- name: Core tasks
  ansible.builtin.include_tasks:
    file: tasks/mac/core.yml
  tags: always
- name: Unix Core collection tasks
  ansible.builtin.include_tasks:
    file: collections/unix-collection.yml
  tags: always
- name: Dotfiles stow
  ansible.builtin.include_tasks:
    file: tasks/mac/dotfiles.yml
  tags: always
