- hosts: localhost
  gather_facts: true
  become: true
  become_user: "{{ lookup('env', 'USER') }}"
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    personal: "{{ lookup('env', 'HOME') }}/personal"
  pre_tasks:
    - name: Update cache
      apt:
      update_cache: true
      become_user: root
      tags:
        - install
        - desktop
  tasks:
    - name: Debian collection tasks
      ansible.builtin.include_tasks:
        file: collections/debian-collection.yml
        include:
          tags:
            - install
            - desktop
      include: always
    - name: Linux Core collection tasks
      ansible.builtin.include_tasks:
        file: collections/linux-collection.yml
        include:
          tags:
            - install
            - desktop
      include: always
    - name: Linux Desktop
      ansible.builtin.include_tasks:
        file: collections/desktop-collection.yml
        include:
          tags:
            - desktop
      include: always
