- hosts: localhost
  gather_facts: true
  become: true
  become_user: "{{ lookup('env', 'USER') }}"
  tasks:
    - name: Linux Desktop
      ansible.builtin.include_tasks:
        file: collections/linux-desktop-collection.yml
