- hosts: localhost
  gather_facts: true
  become: true
  become_user: "{{ lookup('env', 'USER') }}"
  vars:
    source_key: ./.ssh/id_ed25519
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    personal: "{{ lookup('env', 'HOME') }}/personal"
  tasks:
    - name: Mac collection tasks
      ansible.builtin.include_tasks:
        file: collections/mac-collection.yml
      tags: always
    - name: Unix Core collection tasks
      ansible.builtin.include_tasks:
        file: collections/unix-collection.yml
      tags: always
