- name: Install System Packages 1 (build-essential, cmake, pkg-config, pthread)
  become: true
  become_user: root
  community.general.pacman:
    name: ["build-essential", "cmake", "pkg-config", "libpthread-stubs0-dev"]
  tags:
    - core
    - neovim
    - dotfiles

- name: Install System Packages 2 (lua, unzip, libtool, libtool-bin, gettext)
  become: true
  become_user: root
  community.general.pacman:
    name: ["lua5.1", "unzip", "libtool", "libtool-bin", "gettext"]
  tags:
    - core
    - neovim
    - dotfiles

- name: Install System Packages 3 (the rest)
  become: true
  become_user: root
  community.general.pacman:
    name: ["curl", "htop", "golang", "python3-pip", "moreutils", "clangd"]
  tags:
    - core
    - dotfiles
