- name: Install System Packages 1 (build-essential, cmake, pkg-config, pthread)
  become: true
  become_user: root
  apt:
    name: ["build-essential", "cmake", "pkg-config", "libpthread-stubs0-dev"]
  tags:
    - core
    - neovim

- name: Install System Packages 2 (lua, unzip, libtool, libtool-bin, gettext)
  become: true
  become_user: root
  apt:
    name: [ "lua5.1", "unzip", "libtool", "libtool-bin", "gettext", "unrar"]
  tags:
    - core
    - neovim

- name: Install System Packages 3 (the rest)
  become: true
  become_user: root
  apt:
    name: [ "curl", "htop", "golang", "python3-pip", "moreutils", "clangd" ]
  tags:
    - core

- name: Install Clang
  become: true
  become_user: root
  apt:
    name: ["clang", "clang-11", "clang-12", "clangd", "clangd-10", "clangd-11", "clangd-12"]
  tags:
    - neovim
    - core
