- name: Installing stow
  become_user: root
  apt: name=stow

- name: Setup dotfiles
  ansible.builtin.git:
    repo: git@github.com:demestoss/.dotfiles.git
    dest: ~/.dotfiles
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master

- name: Stow debian dotfiles
  shell: cd $HOME/.dotfiles && zsh debian
