- name: Install System Packages 1 (build-essential, cmake, pkg-config, pthread)
  become: true
  become_user: root
  community.general.pacman:
    name: ["cmake", "pkg-config"]
  tags:
    - core
    - neovim
    - dotfiles

- name: Install System Packages 2 (lua, unzip, libtool, libtool-bin, gettext)
  become: true
  become_user: root
  community.general.pacman:
    name: ["lua51", "unzip", "libtool", "gettext", "ripgrep", "fd"]
  tags:
    - core
    - neovim
    - dotfiles

- name: Install System Packages 3 (the rest)
  become: true
  become_user: root
  community.general.pacman:
    name: ["curl", "htop", "moreutils", "direnv"]
  tags:
    - core
    - dotfiles
