- name: Setup dotfiles
  ansible.builtin.git:
    repo: git@github.com:demestoss/.dotfiles.git
    dest: ~/.dotfiles
    recursive: true
    update: true
    accept_hostkey: true
    version: master
- name: Stow debian dotfiles
  shell: cd $HOME/.dotfiles && zsh unix
